package com.jbk.hibernate;
// Generated Apr 17, 2020 1:54:00 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "test")
public class Login implements java.io.Serializable {

	private Integer uname;
	private String passwd;

	public Login() {
	}

	public Login(String passwd) {
		this.passwd = passwd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uname", unique = true, nullable = false)
	public Integer getUname() {
		return this.uname;
	}

	public void setUname(Integer uname) {
		this.uname = uname;
	}

	@Column(name = "passwd", nullable = false, length = 45)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

}
